name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCeN1vT0RegO0nc4uSjC1WRA
          comment_tag_name: YOUTUBE-CARDS
          show_duration: true
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
